UnitTest/Controllers/UserManageController.cs
using Application.Commands.User;
using Application.Services;
using Application.Services.Commands.User;
using Application.Services.Queries.User;
using DomainModel.DTO.UserModel;
using MediatR;
using Microsoft.AspNetCore.Components.Forms;
using Microsoft.AspNetCore.Mvc;
using UnitTest.DTOS;
using UnitTest.ViewModel.User;

namespace UnitTest.Controllers
{
    public class UserManageController : Controller
    {
       
        private readonly IUserCommandService _commandService;
        private readonly IUserQueryService _queryService;
        private readonly IMediator _mediator;
        public UserManageController(IUserCommandService commandService, IUserQueryService queryService,IMediator mediator)
        {
            _commandService = commandService;
            _queryService = queryService;
            this._mediator = mediator;
        }



        public IActionResult Index(UserSearchModel sm)
        {
            return View(sm);
        }
     

        [HttpGet]
        public IActionResult ListAction(UserSearchModel sm)
        {
            return  ViewComponent("UserList", sm);
        }
      

        [HttpGet]
        public IActionResult SearchBoxAction(UserSearchModel sm)
        {
            return  ViewComponent("UserSearchBox", sm);
        }
       
        [HttpGet]
        public IActionResult Add()
        {
            return  ViewComponent("RegisterUser");
        }





        [HttpPost]
        public async Task<JsonResult> Add(UserAddEditViewModel usr)
        {
            try
            {
                var model = new UserAddModel
                {
                    Name = usr.Name,
                    IsDeleted = false
                };


                var insertedUserId = await _mediator.Send(new AddUserCommand(model));

                return Json(new OperationResult
                {
                    success = true,
                    message = "کاربر با موفقیت ثبت شد",
                    id = insertedUserId
                });
            }
            catch (ArgumentException ex)
            {
                return Json(new OperationResult { success = false, message = ex.Message });
            }
            catch (Exception)
            {
                return Json(new OperationResult { success = false, message = "خطا در ثبت کاربر" });
            }

        }

        

        [HttpPost]
        public async Task<JsonResult> DeActiveUser(int id)
        {
            try
            {
                
                var deactivatedUserId = await _mediator.Send(new DeActiveUserCommand(id));

                return Json(new OperationResult
                {
                    success = true,
                    message = "کاربر با موفقیت غیرفعال شد",
                    id = deactivatedUserId
                });
            }
            catch (Exception)
            {
                return Json(new OperationResult
                {
                    success = false,
                    message = "خطا در غیرفعال کردن کاربر"
                });
            }
        }



        [HttpPost]
        public async Task<JsonResult> ActiveUser(int id)
        {
            try
            {
                
                var activatedUserId = await _mediator.Send(new ActiveUserCommand(id));

                return Json(new OperationResult
                {
                    success = true,
                    message = "کاربر با موفقیت فعال شد",
                    id = activatedUserId
                });
            }
            catch (Exception)
            {
                return Json(new OperationResult
                {
                    success = false,
                    message = "خطا در فعال کردن کاربر"
                });
            }
        }

        [HttpGet]
        public IActionResult Update(int UserID)
        {

            return ViewComponent("UpdateUser", UserID);
        }




        [HttpPost]
        public async Task<JsonResult> Update(UserAddEditViewModel usr)
        {
            try
            {
                var model = new UserUpdateModel
                {
                    Id = usr.Id,
                    Name = usr.Name,
                };

                var updatedUserId = await _mediator.Send(new UpdateUserCommand(model));

                return Json(new OperationResult
                {
                    success = true,
                    message = "کاربر با موفقیت ویرایش شد",
                    id = updatedUserId
                });
            }
            catch (ArgumentException ex)
            {
                return Json(new OperationResult { success = false, message = ex.Message });
            }
            catch (Exception)
            {
                return Json(new OperationResult { success = false, message = "خطا در ویرایش کاربر" });
            }
        }





    }
}

UnitTest/VeiwComponents/User/UserListViewComponent.cs
using Application.Queries.User;
using Application.Services;
using Application.Services.Queries.User;
using DomainModel.DTO.UserModel;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using UnitTest.Models.User;

namespace UnitTest.VeiwComponents.User
{
    [ViewComponent(Name = "UserList")]
    public class UserListViewComponent:ViewComponent
    {
        //private readonly IUserService UserSrv;
        private readonly Application.Services.Queries.User.IUserQueryService _queryService;
        private readonly IMediator _mediator;
        public UserListViewComponent(IUserQueryService queryService, IMediator _mediator)
        {
            this._queryService = queryService;
            this._mediator = _mediator;
        }
        public async Task <IViewComponentResult> InvokeAsync(UserSearchModel sm)
        {
            //int rc = 0;
            //var usrs = await _queryService.SearchUsersAsync(sm);
            var usrs = await _mediator.Send(new SearchUsersQuery(sm));
            UserListAndSearchModel hsm = new UserListAndSearchModel { sm = sm, UserListItems = usrs.Users };
            sm.RecordCount = usrs.RecordCount;
            //sm.RecordCount = rc;
            if (sm.PageSize == 0)
            {
                sm.PageSize = 10;
            }
            if (sm.RecordCount % sm.PageSize == 0)
            {
                sm.PageCount = sm.RecordCount / sm.PageSize;
            }
            else
            {
                sm.PageCount = sm.RecordCount / sm.PageSize + 1;

            }
            return View(hsm);
        }
    }
}

UnitTest/VeiwComponents/User/UserSearchBoxViewComponent.cs
using Application.Queries.User;
using Application.Services;
using Application.Services.Queries.User;
using DomainModel.DTO.UserModel;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace UnitTest.VeiwComponents.User
{
    [ViewComponent(Name = "UserSearchBox")]
    public class UserSearchBoxViewComponent: ViewComponent
    {
        //private readonly IUserService UserSrv;
        private readonly IUserQueryService _queryService;
        private readonly IMediator _mediator;
        public UserSearchBoxViewComponent(IUserQueryService queryService, IMediator _mediator)
        {
            this._queryService = queryService;
            this._mediator = _mediator;
        }
        
        public IViewComponentResult Invoke(UserSearchModel sm)
        {
            // اگر اینجا یه موقه دراپ دان داشتیم باید متدشو با send صدا میکنم.
           // var usr = await _mediator.Send(new GetDrpTblNameQuery();
            return View(sm);
        }
    }
}

UnitTest/Views/UserManage/Index.cshtml
@model DomainModel.DTO.UserModel.UserSearchModel

@{
    ViewData["Title"] = "Index";
}

<style>
    tr:hover td {
        background-color: #dcd6d6;
    }
</style>




<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
    <!-- START - MetaTags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="fa">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="~/lib/sweetalert/sweetalert2.min.css" rel="stylesheet">
    <link href="~/lib/sweetalert/sweetalert2.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/select2.min.css" />


</head>




<body class="navbar-top" style="background-color:#ffffff">

   
    <!-- END - Main Navibar -->
    <!-- START - Main Content -->
    <div class="page-container" style="background-color:#ffffff">

        <!-- START - Page Content -->
        <div class="page-content" style="background-color:#ffffff">
            <!-- START - Main Content -->
            <div class="content-wrapper" style="background-color:#ffffff">

               
                <!-- Content area -->
                <div class="content" style="background-color:#ffffff">






                    <div id="dvSearchBox">
                        @await Component.InvokeAsync("UserSearchBox", this.Model)
                    </div>

                    <div id="dvGrid">
                        @await Component.InvokeAsync("UserList", this.Model)
                    </div>






                    <!--start modal1-->


                    <div class="modal fade" id="myModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h1 class="modal-title fs-5" id="staticBackdropLabel"></h1>
                                    <span id="closemodal" type="submit" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa fa-close"></i></span>
                                </div>
                                <div class="modal-body">
                                    <div id="dvContent"></div>
                                </div>

                            </div>
                        </div>
                    </div>

                    <!--End Modal1-->






                </div>
                <!-- Footer -->

                <div class="breadcrumb-line" style="background-color:#ffffff; border-top:1px solid gray; text-align:center; bottom:0px !important; position:fixed; width:100%;">
                    <div class="col-md-offset-2 col-md-6">
                        <span style="color: black;"> - تمامی حقوق متعلق محفوظ می باشد </span>
                    </div>
                </div>
                <!-- /footer -->

            </div>
            <!-- END - Main Content -->

        </div>
        <!-- END - Page Content -->

    </div>
    <!-- END - Main Content -->
    <!--Top Loading-->




   
    <!-- END - theme JS files -->
    <script src="~/lib/jquery/dist/jquery-3.7.1.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
 @*    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.0/js/bootstrap.min.js"></script>
 *@
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/sweetalert/sweetalert2.min.js"></script>
    <script src="~/lib/sweetalert/sweetalert2.js"></script>
    <script src="~/js/select2.min.js"></script>









    


    <script>


        function BindGrid() {
            debugger;
            var SendingUrl = '@Url.Action("ListAction", "UserManage")';
            var SendingData = $("#frmSearchUser").serialize();
            $.get(SendingUrl, SendingData, function (grd) {
                $("#dvGrid").html(grd);
            });
        }




        function RefreshSearchBox() {
            var SendingUrl = '@Url.Action("SearchBoxAction", "UserManage")';
            var SendingData = $("#frmSearchUser").serialize();//ino gozashtam k vaghti k button add ro zadam search ghabli napare
            $.get(SendingUrl, SendingData, function (frmsearch) {
                $("#dvSearchBox").html(frmsearch);
            });
        }

        function SuccessMessage(SuccessTxt) {
            swal({
                title: "اعلان",
                text: SuccessTxt,
                type: "success",
                button: "باشه"
            });
        }

        function ErrorMessage(ErrorTxt) {
            swal({
                title: "خطا",
                text: ErrorTxt,
                type: "error",
                button: "باشه"
            });
        }


        $(document).on("click", ".btnDeActiveUser", function () {
            debugger;
            var id = $(this).attr("data-deactiveUser");
            var Name = $(this).attr("data-Name");
            swal({
                title: 'آیا مطمئنید؟',
                // text: "آیا واقعاً می خواهید این مورد را حذف کنید؟",
                html: `آیا واقعاً می‌خواهید  کاربر : <span style="color: red; font-size: 20px; font-weight: bold;">${Name}</span>

                                را  را غیرفعال کنید؟`, // استفاده از HTML
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'بله، غیرفعال شود',
                cancelButtonText: 'خیر، لغو شود'
            }).then((result) => {
                console.log("Result: ", result);  // بررسی نتیجه SweetAlert
                if (result === true) {  // استفاده مستقیم از result به جای result.isConfirmed

                    var SendingUrl = '@Url.Action("DeActiveUser", "UserManage")';
                    var SendingData = "id=" + id;
                    $.post(SendingUrl, SendingData, function (op) {
                        if (op.success.toString() === "true") {
                            var rowID = "#tr_" + id;
                            //$(rowID).slideUp(500);
                            SuccessMessage(op.message);
                            BindGrid();
                        }
                        else {
                            ErrorMessage(op.message);
                        }
                    });
                }
            });
        });


        $(document).on("click", ".btnActiveUser", function () {
            debugger;
            var id = $(this).attr("data-activeUser");
            var Name = $(this).attr("data-Name");
            swal({
                title: 'آیا مطمئنید؟',
                // text: "آیا واقعاً می خواهید این مورد را حذف کنید؟",
                html: `آیا واقعاً می‌خواهید  کاربر : <span style="color: red; font-size: 20px; font-weight: bold;">${Name}</span>

                                را  را فعال کنید؟`, // استفاده از HTML
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'بله، فعال شود',
                cancelButtonText: 'خیر، لغو شود'
            }).then((result) => {
                console.log("Result: ", result);  // بررسی نتیجه SweetAlert
                if (result === true) {  // استفاده مستقیم از result به جای result.isConfirmed

                    var SendingUrl = '@Url.Action("ActiveUser", "UserManage")';
                    var SendingData = "id=" + id;
                    $.post(SendingUrl, SendingData, function (op) {
                        if (op.success.toString() === "true") {
                            var rowID = "#tr_" + id;
                            //$(rowID).slideUp(500);
                            SuccessMessage(op.message);
                            BindGrid();
                        }
                        else {
                            ErrorMessage(op.message);
                        }
                    });
                }
            });
        });


        $(document).on("click", "#btnAddUser", function () {
            var url = $(this).attr("data-action");
            var container = $(this).attr("data-container");
            var modal = $(this).attr("data-modal-id");
            $.get(url, null, function (rd) {
                $("#" + container).html(rd);
                $("#" + modal).modal('show');
            });
        });



        $(document).on("click", "#btnAddinternalUser", function () {
            debugger;
            var modal = $(this).attr("data-modal-id");
            var action = $(this).attr("data-action");
            var method = $(this).attr("data-method");
            var formid = "#" + $(this).attr("data-form-id");
            if (method === "post") {
                var SendingData = $(formid).serialize();
                $.post(action, SendingData, function (op) {

                    if (op.success.toString() === "true") {
                        $("#myModal").modal('hide');
                        SuccessMessage(op.message);

                        //alert(op.message);
                        BindGrid();
                        RefreshSearchBox();
                    }
                    else {
                        //alert(op.message);
                         $("#myModal").modal('hide');
                        ErrorMessage(op.message);

                    }
                });
            }
        });





        $(document).on("click", ".btnUpdateUser", function () {
            var id = $(this).attr("data-UpdateUser");
            let sendingUrl = '@Url.Action("Update", "UserManage")';
            let sendingData = "UserID=" + id;
            $.get(sendingUrl, sendingData, function (frm) {
                $("#dvContent").html(frm);
                $("#myModal").modal('show');
            });
        });

        $(document).on("click", "#btnUpdateinternalUser", function () {
            var id = $(this).attr("data-updateinternalUser");
            let sendingUrl = '@Url.Action("Update", "UserManage")';
            let sendingData = $("#frmupdateUser").serialize();
            $.post(sendingUrl, sendingData, function (op) {
                if (op.success.toString() === "true") {
                    $("#myModal").modal('hide');
                    SuccessMessage(op.message);
                    BindGrid();
                    RefreshSearchBox();
                }
                else {
                      $("#myModal").modal('hide');
                    ErrorMessage(op.message);
                }
            });

        });

        $(document).on("click", "#btnCancelEditUser", function () {
            $("#myModal").modal('hide');
        });



        





        $(document).on("keyup", "#Name", function () {
            BindGrid();
        });
        

     

        $(document).on("click", "#btnCancelAddUser", function () {
            $("#myModal").modal('hide');
        });

        $(document).on("click", "#closemodal", function () {
            $("#myModal").modal('hide');
        });




       
    </script>



</body>

</html>